// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// displacements
Rcpp::DataFrame displacements(Rcpp::StringVector uniqueIds, Rcpp::DatetimeVector timeStamps, int marginInSeconds);
RcppExport SEXP _FeedrRewrite_displacements(SEXP uniqueIdsSEXP, SEXP timeStampsSEXP, SEXP marginInSecondsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type uniqueIds(uniqueIdsSEXP);
    Rcpp::traits::input_parameter< Rcpp::DatetimeVector >::type timeStamps(timeStampsSEXP);
    Rcpp::traits::input_parameter< int >::type marginInSeconds(marginInSecondsSEXP);
    rcpp_result_gen = Rcpp::wrap(displacements(uniqueIds, timeStamps, marginInSeconds));
    return rcpp_result_gen;
END_RCPP
}
// encounters
Rcpp::DataFrame encounters(Rcpp::StringVector uniqueIds, Rcpp::DatetimeVector timeStamps, int marginInSeconds);
RcppExport SEXP _FeedrRewrite_encounters(SEXP uniqueIdsSEXP, SEXP timeStampsSEXP, SEXP marginInSecondsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type uniqueIds(uniqueIdsSEXP);
    Rcpp::traits::input_parameter< Rcpp::DatetimeVector >::type timeStamps(timeStampsSEXP);
    Rcpp::traits::input_parameter< int >::type marginInSeconds(marginInSecondsSEXP);
    rcpp_result_gen = Rcpp::wrap(encounters(uniqueIds, timeStamps, marginInSeconds));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FeedrRewrite_displacements", (DL_FUNC) &_FeedrRewrite_displacements, 3},
    {"_FeedrRewrite_encounters", (DL_FUNC) &_FeedrRewrite_encounters, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_FeedrRewrite(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
